pipeline:
  build:
    name: build
    image: maven:3-jdk-8
    commands:
      - "mvn -Prelease -DskipTests clean install"
    depends_on: [ "clone" ]
  docker:
    name: docker
    image: plugins/docker
    DOCKER_LAUNCH_DEBUG: true
    repo: rocketmq/rocketmq
    registry: hz.4yutech.com:7070
    insecure: true
    tags: latest
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    depends: [ "build" ]
  dingtalk:
    name: dingtalk
    image: chinaloryu/dingtalk
    token:
      from_secret: dingding
    debug: true
    type: markdown
    message_color: true
    sha_link: true
    when:
      status: [ success, failure ]
