---
kind: "pipeline"
name: "default"
steps:
  - name: "publish"
    image: plugins/docker
    repo: chinaloryu/rocketmq
    registry: http://hz.4yutech.com:7070/rocketmq
    tags: "hz.4yutech.com:7070/rocketmq/test:latest"
    environment:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      # dockerfile: "Dockerfile"
      # tags: "${DRONE_BUILD_NUMBER}"
    depends_on: [ "clone" ]

trigger:
  branch:
  - release
