pipeline:
  build:
    name: build
    image: maven:3-jdk-8
    commands:
      - "mvn clean package"
    depends_on: [ "clone" ]
  docker:
    name: docker
    image: plugins/docker
    DOCKER_LAUNCH_DEBUG: true
    registry: hz.4yutech.com:7070/chinaloryu
    insecrue: true
    repo: rocketmq
    tags: latest
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    depends: [ "build" ]
  dingtalk:
    name: dingtalk
    image: lddsb/drone-dingtalk-message
    token: 
      from_secret: [ DINGTALK_TOKEN ]
    type: markdown
    message_color: true
    sha_link: true
