---
kind: "pipeline"
name: "publish"
steps:
  - name: "publish"
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    settings:
      DOCKER_LAUNCH_DEBUG: 'true'
      insecure: true
      registry: http://192.168.2.100:7070
      repo: 192.168.2.100:7070/rocketmq/rocketmq
      tags:
        - "${DRONE_BUILD_NUMBER}"
        - latest
        - '0.1'
      # dockerfile: "Dockerfile"
    depends_on: [ "clone" ]

trigger:
  branch:
  - release
