---
kind: "pipeline"
name: "default"
steps:
  - name: "publish"
    image: alpine
    repo: chinaloryu/rocketmq
    commands:
      - echo $username, $password
    environment:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      # dockerfile: "Dockerfile"
      # tags: "${DRONE_BUILD_NUMBER}"
    depends_on: [ "clone" ]

trigger:
  branch:
  - release
