---
kind: "pipeline"
name: "publish"
steps:
  - name: "publish"
    image: plugins/docker
    secrets: [ "docker_username","docker_password" ]
    settings:
      repo: chinaloryu/rocketmq
      tags:
        - "${DRONE_BUILD_NUMBER}"
        - latest
        - '0.1'
      # dockerfile: "Dockerfile"
    depends_on: [ "clone" ]

trigger:
  branch:
  - release
