pipeline:
  build:
    name: build
    image: maven:3-jdk-8
    commands:
      - "mvn clean package"
    depends_on: [ "clone" ]
  docker:
    name: docker
    image: plugins/docker
    repo: chinaloryu/rocketmq
    tags: latest
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    depends: [ "build" ]