pipeline:
  build:
    name: build
    image: maven:3-jdk-8
    commands:
      - "mvn -Prelease -DskipTests clean install"
    depends_on: [ "clone" ]
  docker:
    name: docker
    image: plugins/docker
    DOCKER_LAUNCH_DEBUG: true
    repo: chinaloryu/rocketmq
    tags: latest
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    depends: [ "build" ]
  dingtalk:
    name: dingtalk
    image: lddsb/drone-dingtalk-message
    secrets: [ dingding ]
    settings:
      token:
        from_secret: dingding
      type: markdown
      message_color: true
      sha_link: true