---
kind: "pipeline"
name: "default"
steps:
  - name: "build"
    image: maven:3-jdk-8
    commands:
      - "mvn -Prelease-all -DskipTests clean install -U"
    depends_on: [ "clone" ]
  - name: "publish"
    image: plugins/docker
    repo: chinaloryu/rocketmq
    registry: http://hz.4yutech.com:7070/rocketmq
    tags: 
      - latest
      - test
    environment:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      # dockerfile: "Dockerfile"
      # tags: "${DRONE_BUILD_NUMBER}"
    depends_on: [ "build" ]

trigger:
  branch:
  - release
