---
kind: "pipeline"
name: "publish"
steps:
  - name: "publish"
    image: plugins/docker
    settings:
      USERNAME:
        from-secret: docker_username
      PASSWORD:
        from-secret: docker_password
      repo: chinaloryu/rocketmq
      tags:
        - "${DRONE_BUILD_NUMBER}"
        - latest
        - '0.1'
      # dockerfile: "Dockerfile"
    depends_on: [ "clone" ]

trigger:
  branch:
  - release
