pipeline:
  dingtalk:
    name: dingtalk
    image: guoxudongdocker/drone-dingtalk 
    settings:
      token: 
        from_secret: dingding
      type: markdown
      message_color: true
      message_pic: true
      sha_link: true
  when:
    status: [failure, success]