---
kind: "pipeline"
name: "publish"
steps:
  - name: "publish"
    image: plugins/docker
    repo: chinaloryu/rocketmq
    registry: http://hz.4yutech.com:7070/rocketmq
    environment:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      # dockerfile: "Dockerfile"
      # tags: "${DRONE_BUILD_NUMBER}"

trigger:
  branch:
  - release
