---
kind: "pipeline"
name: "default"
steps:
  - name: "compile"
    image: maven:3-jdk-8
    commands:
      - "mvn clean package"
    depends_on: [ "clone" ]
  - name: "build"
    image: maven:3-jdk-8
    commands:
      - "mvn -Prelease-all -DskipTests clean install -U"
    depends_on: [ "compile" ]
  - name: "publish"
    image: plugins/docker
    repo: chinaloryu/rocketmq
    commands:
      - "echo ${username},${password}"
    environment:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      # dockerfile: "Dockerfile"
      # tags: "${DRONE_BUILD_NUMBER}"
    depends_on: [ "build" ]

trigger:
  branch:
  - release
